### ISSUE TITLE
Major refactor.  Should I hard-fork?

### ISSUE THREAD

**Issue by dmopalmer** [charkster/rigol_ds1054z#3]
I am doing a major refactor of this code which includes/will include

- Bringing the code to modern python and pyvisa, starting with #2 pull request from @battlecoder
- Reformat with Black to PEP8 (including changing from tab indent to spaces)
-- I am protecting the table-like parts of the code so they don't rewrap.
- Packaging it to be pip-installable as an importable module
- Making the running commentary optional.  (Probably just a verbose flag, as opposed to doing it right and using the logging system)
- Binary transfer instead of ASCII, to support long readouts and selective readouts.

You can see the changes in [my `packaging` branch](https://github.com/dmopalmer/rigol_ds1054z/tree/packaging) (work in progress).

At some point, even if most of the lines of code are exactly the same, the change in structure makes it a different package, or at least hard to merge without conflict.  Then the choices are:
1. Pull-request the changes back to the main @charkster repo and call it version 2
2. Hard fork it with a new name and copious crediting in the README

What is your preference?

**Comment by charkster** [comment]
Hi @battlecoder I would prefer 2, and you are free to take as many parts of the code as you would like. If you put a link to my repo on your new README, you don't need to put any other references in your code. Thanks for taking an interest in this repo.

**Comment by battlecoder** [comment]
@charkster , It's @dmopalmer who is forking your code, not me.
Although I'm happy that my PR is going to be useful to someone else to update and extend what you have generously shared with us here.

**Comment by charkster** [comment]
@dmopalmer, sorry I sent your response to @battlecoder by accident. Use/change any parts you want, just make it better. Thanks.
